import type { Element, ElementContent, Parent, Root } from "hast"

import { h } from "hastscript"
import { SKIP, visit } from "unist-util-visit"

import { footnoteHeadingId } from "../../components/constants"
import { QuartzTransformerPlugin } from "../types"

export interface FootnoteLocation {
  node: Element
  parent: Parent
  index: number
}

/**
 * Checks if an element is a footnote list item.
 * Footnote list items have IDs starting with "user-content-fn-".
 */
export function isFootnoteListItem(child: ElementContent): boolean {
  if (child.type !== "element") {
    return false
  }
  const id = child.properties?.id?.toString()
  return child.tagName === "li" && Boolean(id?.startsWith("user-content-fn-"))
}

/** Locates the `<ol>` of footnote list items in `tree`, returning its node + parent + index. */
export function findFootnoteList(tree: Root): FootnoteLocation | null {
  let footnoteLocation: FootnoteLocation | null = null

  visit(tree, "element", (node, index, parent) => {
    if (
      node.tagName === "ol" &&
      node.children.some(isFootnoteListItem) &&
      parent !== undefined &&
      index !== undefined
    ) {
      footnoteLocation = { node, parent, index }
      return SKIP
    }
    return null
  })

  return footnoteLocation
}

/** Href prefix that identifies a footnote reference anchor (`<sup><a href="#user-content-fn-…">`). */
const FOOTNOTE_REF_HREF_PREFIX = "#user-content-fn"

/** True if `element` is a `<sup>` wrapping a footnote-reference anchor. */
function isFootnoteRefSup(element: Element): boolean {
  return (
    element.tagName === "sup" &&
    element.children.some(
      (grandchild) =>
        grandchild.type === "element" &&
        grandchild.tagName === "a" &&
        typeof grandchild.properties?.href === "string" &&
        grandchild.properties.href.startsWith(FOOTNOTE_REF_HREF_PREFIX),
    )
  )
}

/**
 * Removes footnote-reference `<sup>` elements from `node`'s subtree (in document
 * order) and appends them to `collected`. Recurses into nested inline wrappers so
 * a footnote ref inside `<em>`/`<strong>` is still extracted.
 */
function extractFootnoteRefSups(node: Element, collected: Element[]): void {
  const kept: ElementContent[] = []
  for (const child of node.children) {
    if (child.type === "element") {
      if (isFootnoteRefSup(child)) {
        collected.push(child)
        continue
      }
      extractFootnoteRefSups(child, collected)
    }
    kept.push(child)
  }
  node.children = kept
}

/**
 * Hoists footnote references out of enclosing links. A footnote ref nested
 * inside an `<a>` produces invalid nested anchors (`<a><sup><a>…</a></sup></a>`),
 * which browsers silently split—breaking the link and the footnote's styling.
 * Moving each ref to immediately after its enclosing link yields valid HTML and
 * lets the favicon pass attach to the link's real text.
 */
export function hoistFootnotesOutOfLinks(tree: Root): void {
  visit(tree, "element", (node, index, parent) => {
    if (
      node.tagName !== "a" ||
      parent === undefined ||
      index === undefined ||
      typeof node.properties?.href !== "string" ||
      node.properties.href.startsWith(FOOTNOTE_REF_HREF_PREFIX)
    ) {
      return undefined
    }

    const collected: Element[] = []
    extractFootnoteRefSups(node, collected)
    if (collected.length > 0) {
      parent.children.splice(index + 1, 0, ...(collected as ElementContent[]))
    }
    return SKIP
  })
}

/** The ID that mdast-util-to-hast hardcodes on the footnotes heading */
const UPSTREAM_FOOTNOTE_HEADING_ID = "footnote-label"

/** IDs that identify a footnote heading (upstream uses "footnote-label", we normalize to "footnotes") */
const FOOTNOTE_HEADING_IDS: ReadonlySet<string> = new Set([
  footnoteHeadingId,
  UPSTREAM_FOOTNOTE_HEADING_ID,
])

/** True if `id` matches a recognized footnote-heading id (ours or remark-gfm's). */
function isFootnoteHeadingId(id: unknown): boolean {
  return typeof id === "string" && FOOTNOTE_HEADING_IDS.has(id)
}

/** True if the section already contains a footnote heading (h1 or h2 with a known id). */
export function hasFootnoteHeading(sectionElement: Element): boolean {
  return sectionElement.children.some((child: ElementContent) => {
    // Check for both h1 and h2 (remark-gfm-footnotes generates h2)
    if (child.type !== "element" || (child.tagName !== "h1" && child.tagName !== "h2")) {
      return false
    }
    return isFootnoteHeadingId(child.properties?.id)
  })
}

/** Creates the visually-hidden `<h1>` "Footnotes" heading used for the footnotes section. */
export function createFootnoteHeading(): Element {
  return h("h1", { id: footnoteHeadingId, className: ["sr-only"] }, ["Footnotes"])
}

/**
 * Ensures the footnote section has an h1 heading. If an h2 heading exists
 * (as generated by remark-gfm), it is upgraded to h1. If no heading exists,
 * one is added.
 */
export function addHeadingToSection(sectionElement: Element): void {
  const existingHeading = sectionElement.children.find(
    (child: ElementContent) =>
      child.type === "element" &&
      (child.tagName === "h1" || child.tagName === "h2") &&
      isFootnoteHeadingId(child.properties?.id),
  ) as Element | undefined

  if (existingHeading) {
    existingHeading.tagName = "h1"
    existingHeading.properties = {
      ...existingHeading.properties,
      id: footnoteHeadingId,
      className: ["sr-only"],
    }
    // Update any autolinked anchor inside the heading (rehypeAutolinkHeadings wraps
    // heading text in <a href="#old-id">) to point to the normalized ID
    for (const child of existingHeading.children) {
      if (
        child.type === "element" &&
        child.tagName === "a" &&
        typeof child.properties?.href === "string" &&
        child.properties.href === `#${UPSTREAM_FOOTNOTE_HEADING_ID}`
      ) {
        child.properties.href = `#${footnoteHeadingId}`
      }
    }
  } else {
    sectionElement.children.unshift(createFootnoteHeading() as ElementContent)
  }
}

/**
 * Checks if the parent is already a properly wrapped footnote section.
 */
export function isAlreadyWrapped(parent: Parent): parent is Element {
  if (parent.type !== "element") {
    return false
  }
  const element = parent as Element
  if (element.tagName !== "section") {
    return false
  }
  const dataFootnotes = element.properties?.dataFootnotes ?? element.properties?.["data-footnotes"]
  return dataFootnotes === true || dataFootnotes === ""
}

/**
 * Creates a properly wrapped footnote section with heading.
 */
export function createFootnoteSection(footnoteList: Element): Element {
  return h("section", { dataFootnotes: true, className: ["footnotes"] }, [
    createFootnoteHeading(),
    footnoteList,
  ])
}

/**
 * Removes "Footnotes" text from iframe children.
 */
export function cleanupIframeFootnoteText(tree: Root): void {
  visit(tree, "element", (node) => {
    if (node.tagName !== "iframe") {
      return
    }
    node.children = node.children.filter(
      /* istanbul ignore next -- iframe children are always text nodes in practice */
      (child) => {
        if (child.type === "text") {
          const trimmed = child.value.trim()
          return trimmed !== "Footnotes" && trimmed !== ""
        }
        return true
      },
    )
  })
}

/**
 * Fixes malformed footnotes sections that can occur when raw HTML (like iframes)
 * appears at the end of a document. The issue manifests as:
 * 1. Missing <section data-footnotes> wrapper
 * 2. Missing or wrong-level heading (remark-gfm generates h2 instead of h1)
 * 3. Footnotes text content appearing inside iframe tags
 *
 * This plugin:
 * 1. Finds footnote lists (ol elements with li children that have user-content-fn- ids)
 * 2. Ensures they're wrapped in a proper section with data-footnotes attribute
 * 3. Adds the footnotes heading if missing
 * 4. Cleans up any text nodes that were placed incorrectly in iframes
 */
export const FixFootnotes: QuartzTransformerPlugin = () => {
  return {
    name: "FixFootnotes",
    htmlPlugins() {
      return [
        () => {
          return (tree: Root) => {
            hoistFootnotesOutOfLinks(tree)

            const location = findFootnoteList(tree)

            if (!location) {
              return
            }

            // Check if the list is already properly wrapped in a section with data-footnotes
            if (isAlreadyWrapped(location.parent)) {
              addHeadingToSection(location.parent)
            } else {
              // Clean up any text nodes that contain "Footnotes" from preceding iframes
              cleanupIframeFootnoteText(tree)

              // Create the proper section wrapper and replace the ol
              const footnoteSection = createFootnoteSection(location.node)
              location.parent.children[location.index] = footnoteSection as ElementContent
            }

            // Rename aria-describedby from upstream "footnote-label" to "footnotes"
            visit(tree, "element", (node) => {
              const describedBy = node.properties?.ariaDescribedBy
              if (
                Array.isArray(describedBy) &&
                describedBy.includes(UPSTREAM_FOOTNOTE_HEADING_ID) &&
                node.properties
              ) {
                node.properties.ariaDescribedBy = describedBy.map((v) =>
                  v === UPSTREAM_FOOTNOTE_HEADING_ID ? footnoteHeadingId : v,
                )
              }
            })
          }
        },
      ]
    },
  }
}
