/**
 * Precomputed dark-mode image swap at runtime.
 *
 * The `InvertInDarkMode` transformer wraps every label-eligible `<img>`
 * in a `<picture>` whose `<source media="prefers-color-scheme: dark"
 * srcset>` points at the precomputed `<basename>-inverted.<ext>` sibling
 * generated by `scripts/generate_inverted_variants.py`. The browser
 * fetches the right variant natively per system preference; this module
 * only swaps `img.src` when the user's manual toggle disagrees with the
 * system.
 */

import { forceHslInvertClass, invertInDarkModeClass } from "../constants"
import { invertedUrl, isInvertedUrl } from "./invertedAssets"

const INVERT_SELECTOR = `img.${invertInDarkModeClass}, img.${forceHslInvertClass}`
const REVERTABLE_SELECTOR = `img.${invertInDarkModeClass}:not(.${forceHslInvertClass})[data-invert-original-src]`
const PICTURE_INVERT_SELECTOR = `picture > img.${invertInDarkModeClass}:not(.${forceHslInvertClass})`

/** Reads `<html data-theme>` — set synchronously by `detectInitialState.js`. */
export function isDarkMode(): boolean {
  return document.documentElement.getAttribute("data-theme") === "dark"
}

/** True iff this image should be HSL-processed in the current theme. */
export function shouldProcess(img: HTMLImageElement): boolean {
  return img.classList.contains(forceHslInvertClass) || isDarkMode()
}

/**
 * True iff `<img>` is the direct child of a `<picture>`.
 */
export function isInsidePicture(img: HTMLImageElement): boolean {
  return img.parentElement?.tagName === "PICTURE"
}

export function processPictureImage(img: HTMLImageElement): boolean {
  img.dataset["invertOriginalSrc"] ??= img.src
  const inverted = invertedUrl(img.dataset["invertOriginalSrc"])
  if (img.currentSrc && isInvertedUrl(img.currentSrc)) {
    img.src = inverted
    img.dataset["invertProcessed"] = "1"
    return true
  }
  img.addEventListener(
    "load",
    () => {
      // Guard against a fast revert beating the swap to the load
      // event: the handler is `{once: true}` and stays armed, but if
      // we got reverted first (img.src now points at the original
      // again) the load fires for the wrong resource. Skipping the
      // marker there keeps a future dark-toggle from short-circuiting
      // in `processImage`.
      if (isInvertedUrl(img.currentSrc)) {
        img.dataset["invertProcessed"] = "1"
      }
    },
    { once: true },
  )
  img.src = inverted
  return true
}

/** Overrides `<source>` srcset so the manual theme toggle wins over the
 *  system `prefers-color-scheme` media query on the `<picture>`. */
function setPictureSourceSrcset(img: HTMLImageElement, srcset: string): void {
  const source = img.parentElement?.querySelector("source")
  if (source) source.srcset = srcset
}

/**
 * Returns `false` for ineligible images (wrong theme, already processed,
 * not yet decoded, not inside `<picture>`).
 */
export function processImage(img: HTMLImageElement): Promise<boolean> {
  if (!shouldProcess(img)) return Promise.resolve(false)
  if (img.dataset["invertProcessed"]) return Promise.resolve(false)
  if (!img.complete || img.naturalWidth === 0) return Promise.resolve(false)
  if (isInsidePicture(img)) return Promise.resolve(processPictureImage(img))
  return Promise.resolve(false)
}

/** Restore a processed image to its original src (theme switched to light). */
export function revertImage(img: HTMLImageElement): boolean {
  const original = img.dataset["invertOriginalSrc"]
  if (!original) return false
  img.src = original
  if (isInsidePicture(img)) setPictureSourceSrcset(img, original)
  delete img.dataset["invertProcessed"]
  return true
}

/**
 * Capture-phase document listener. `load` doesn't bubble, so capture is
 * required to catch it at the document level — which is what lets a
 * single listener installed in `<head>` cover every `<img>` in the body.
 */
export function handleLoadEvent(event: Event): void {
  const target = event.target
  if (target instanceof HTMLImageElement && target.matches(INVERT_SELECTOR)) {
    void processImage(target)
  }
}

/** Sweep `root` for already-decoded eligible images and process them. */
export function processLoaded(root: Document | Element = document): void {
  const images = root.querySelectorAll<HTMLImageElement>(INVERT_SELECTOR)
  for (const img of images) {
    if (img.complete && img.naturalWidth > 0) {
      void processImage(img)
    }
  }
}

/** Revert every processed image under `root` (used when theme → light). */
export function revertProcessed(root: Document | Element = document): void {
  const images = root.querySelectorAll<HTMLImageElement>(REVERTABLE_SELECTOR)
  for (const img of images) {
    revertImage(img)
  }
}

/** Ensure every `<picture>` `<source>` srcset matches the active theme,
 *  including images that haven't loaded yet (lazy / below the fold). */
export function syncPictureSources(root: Document | Element = document): void {
  const dark = isDarkMode()
  for (const img of root.querySelectorAll<HTMLImageElement>(PICTURE_INVERT_SELECTOR)) {
    const original = img.dataset["invertOriginalSrc"] ?? img.src
    setPictureSourceSrcset(img, dark ? invertedUrl(original) : original)
  }
}

/** Reactive bridge between the theme attribute and image state. */
export function onThemeChange(): void {
  if (isDarkMode()) {
    processLoaded()
  } else {
    revertProcessed()
  }
  syncPictureSources()
}
