/**
 * Per-pixel HSL inversion in dark mode: invert the HSL `L` channel while
 * keeping `H` and `S` exact (no sRGB-matrix approximation, which is what
 * CSS `hue-rotate` and our SVG `feColorMatrix` fallback both do).
 *
 * Loaded via `PageShell.beforeDOMLoaded` → bundled into `prescript.js` →
 * runs synchronously in `<head>` before the body parses. That means the
 * capture-phase `load` listener installed by the inline bootstrap is
 * attached *before any `<img>` is created*, so it catches every image
 * load event in time for first paint.
 *
 * Two opt-in classes:
 *   - `.invert-in-dark-mode`: only active when `<html data-theme="dark">`.
 *     Reverts on theme switch to light.
 *   - `.force-hsl-invert`: always active, regardless of theme. Used for
 *     demo subfigures and any image we want pre-inverted at the source.
 *
 * Raster path: the `InvertInDarkMode` transformer wraps every label-
 * eligible `<img>` in a `<picture>` whose `<source media="prefers-color-
 * scheme: dark" srcset>` points at the precomputed
 * `<basename>-inverted.<ext>` sibling generated by
 * `scripts/generate_inverted_variants.py`. The browser fetches the right
 * variant natively per system preference; this module's JS only swaps
 * `img.src` when the user's manual toggle disagrees with the system. No
 * canvas reads — no Firefox anti-fingerprinting prompt.
 *
 * SVG path: at runtime we fetch the source, rewrite every color-bearing
 * attribute / CSS declaration via `d3-color`, and swap the src to an
 * inverted `data:image/svg+xml` URL. Vector fidelity preserved.
 *
 * Cross-origin SVGs without `Access-Control-Allow-Origin` make the fetch
 * fail; we swallow the error and leave the CSS `feColorMatrix` filter
 * fallback in effect for those images.
 */

import { hsl, color as parseColor } from "d3-color"

import { forceHslInvertClass, invertInDarkModeClass } from "../constants"
import { invertedUrl, isInvertedUrl } from "./invertedAssets"

const INVERT_SELECTOR = `img.${invertInDarkModeClass}, img.${forceHslInvertClass}`
// Revert target = "we stashed an original on this img" rather than "we
// finished processing". With the deferred processed-marker fix, a 404
// swap leaves processed unset but original stashed — we still want to
// revert it on theme switch. `:not(.force-hsl-invert)` keeps
// force-invert imgs inverted across light mode.
const REVERTABLE_SELECTOR = `img.${invertInDarkModeClass}:not(.${forceHslInvertClass})[data-invert-original-src]`

// SVG paint/colored properties we rewrite — both as XML attributes and as
// CSS declarations inside `style="…"` and `<style>` blocks. `currentColor`,
// `none`, paint refs like `url(#grad)`, and `transparent` fall through
// untouched because `d3-color`'s `color()` returns `null` or a non-
// displayable result for them.
const SVG_COLOR_ATTRS = [
  "fill",
  "stroke",
  "stop-color",
  "color",
  "flood-color",
  "lighting-color",
] as const
const SVG_COLOR_PROP_RE = new RegExp(
  `(?<prop>${SVG_COLOR_ATTRS.join("|")})(?<sep>\\s*:\\s*)(?<value>\\S[^;}"']*)`,
  "gi",
)

/**
 * Inverts a single CSS color token's HSL lightness. Returns `null` when the
 * token isn't a displayable color (`none`, `currentColor`, `url(...)`,
 * `transparent`, garbage), letting callers leave the source untouched.
 */
export function invertColorToken(token: string): string | null {
  const c = parseColor(token)
  if (!c || !c.displayable()) return null
  const h = hsl(c)
  h.l = 1 - h.l
  return h.formatHex()
}

/** Rewrites color values inside a CSS declaration string (inline or block). */
export function invertCssColors(css: string): string {
  return css.replace(SVG_COLOR_PROP_RE, (match, ..._args) => {
    const groups = _args.at(-1) as { prop: string; sep: string; value: string }
    const inverted = invertColorToken(groups.value.trim())
    return inverted ? `${groups.prop}${groups.sep}${inverted}` : match
  })
}

/** True iff `src` points at an SVG (case-insensitive, ignores query/hash). */
export function isSvgSrc(src: string): boolean {
  const path = src.split(/[?#]/, 1)[0]
  return path.toLowerCase().endsWith(".svg")
}

/**
 * Parses SVG text, HSL-inverts every color-bearing attribute and CSS
 * declaration, and re-serializes. Returns the original text unchanged if
 * the document fails to parse.
 */
export function invertSvgSource(text: string): string {
  const doc = new DOMParser().parseFromString(text, "image/svg+xml")
  if (doc.getElementsByTagName("parsererror").length > 0) return text
  for (const el of Array.from(doc.documentElement.querySelectorAll<Element>("*"))) {
    for (const attr of SVG_COLOR_ATTRS) {
      const v = el.getAttribute(attr)
      if (!v) continue
      const inverted = invertColorToken(v.trim())
      if (inverted) el.setAttribute(attr, inverted)
    }
    const style = el.getAttribute("style")
    if (style) el.setAttribute("style", invertCssColors(style))
    if (el.tagName.toLowerCase() === "style" && el.textContent) {
      el.textContent = invertCssColors(el.textContent)
    }
  }
  return new XMLSerializer().serializeToString(doc.documentElement)
}

/** Reads `<html data-theme>` — set synchronously by `detectInitialState.js`. */
export function isDarkMode(): boolean {
  return document.documentElement.getAttribute("data-theme") === "dark"
}

/** True iff this image should be HSL-processed in the current theme. */
export function shouldProcess(img: HTMLImageElement): boolean {
  return img.classList.contains(forceHslInvertClass) || isDarkMode()
}

/**
 * True iff `<img>` is the direct child of a `<picture>`. Build-time
 * wrapping (`InvertInDarkMode` transformer) puts every label-eligible
 * raster in a `<picture>` whose `<source media="prefers-color-scheme:
 * dark">` lets the browser fetch the precomputed inverted variant
 * without a canvas round-trip.
 */
export function isInsidePicture(img: HTMLImageElement): boolean {
  return img.parentElement?.tagName === "PICTURE"
}

/**
 * Picture-wrapped raster path. Always stash the original src and set
 * `img.src` to the inverted variant so the attribute aligns with what
 * the user should see in dark mode (browser-picked-inverted from the
 * `<picture>` source becomes a cache hit; mismatch case actually
 * fetches). The processed marker — which CSS keys off to drop the
 * feColorMatrix fallback — is set immediately when the browser
 * already picked the inverted source, otherwise deferred to the
 * `load` event so a 404 / slow swap leaves the filter approximating
 * instead of flashing to the raw light bitmap.
 */
export function processPictureRaster(img: HTMLImageElement): boolean {
  img.dataset["invertOriginalSrc"] ??= img.src
  const inverted = invertedUrl(img.dataset["invertOriginalSrc"])
  if (img.currentSrc && isInvertedUrl(img.currentSrc)) {
    img.src = inverted
    img.dataset["invertProcessed"] = "1"
    return true
  }
  img.addEventListener(
    "load",
    () => {
      // Guard against a fast revert beating the swap to the load
      // event: the handler is `{once: true}` and stays armed, but if
      // we got reverted first (img.src now points at the original
      // again) the load fires for the wrong resource. Skipping the
      // marker there keeps a future dark-toggle from short-circuiting
      // in `processImage`.
      if (isInvertedUrl(img.currentSrc)) {
        img.dataset["invertProcessed"] = "1"
      }
    },
    { once: true },
  )
  img.src = inverted
  return true
}

/**
 * SVG path: fetches the source, HSL-inverts every color attribute /
 * CSS declaration, and swaps src to an inverted `data:image/svg+xml`
 * URL — preserving vector fidelity (a raster path would rasterize).
 * `invertProcessing` guards against concurrent re-entry (a fresh `load`
 * event plus a theme-change sweep could otherwise both fire fetches);
 * `invertProcessed` is only set on success, so the CSS filter fallback
 * remains in effect until the swap lands.
 */
export async function processSvgImage(img: HTMLImageElement): Promise<boolean> {
  if (img.dataset["invertProcessing"]) return false
  img.dataset["invertProcessing"] = "1"
  try {
    const response = await fetch(img.src)
    if (!response.ok) return false
    const inverted = invertSvgSource(await response.text())
    img.dataset["invertOriginalSrc"] ??= img.src
    img.src = `data:image/svg+xml;utf8,${encodeURIComponent(inverted)}`
    img.dataset["invertProcessed"] = "1"
    return true
  } catch {
    return false
  } finally {
    delete img.dataset["invertProcessing"]
  }
}

/**
 * Dispatches to the picture or SVG path. Returns `false` for ineligible
 * images (wrong theme, already processed, not yet decoded); otherwise
 * a `Promise<boolean>` resolving to whether the inversion actually swapped
 * the src.
 */
export function processImage(img: HTMLImageElement): Promise<boolean> {
  if (!shouldProcess(img)) return Promise.resolve(false)
  if (img.dataset["invertProcessed"]) return Promise.resolve(false)
  if (!img.complete || img.naturalWidth === 0) return Promise.resolve(false)
  if (isSvgSrc(img.src)) return processSvgImage(img)
  if (isInsidePicture(img)) return Promise.resolve(processPictureRaster(img))
  return Promise.resolve(false)
}

/** Restore a processed image to its original src (theme switched to light). */
export function revertImage(img: HTMLImageElement): boolean {
  const original = img.dataset["invertOriginalSrc"]
  if (!original) return false
  img.src = original
  delete img.dataset["invertProcessed"]
  return true
}

/**
 * Capture-phase document listener. `load` doesn't bubble, so capture is
 * required to catch it at the document level — which is what lets a
 * single listener installed in `<head>` cover every `<img>` in the body.
 */
export function handleLoadEvent(event: Event): void {
  const target = event.target
  if (target instanceof HTMLImageElement && target.matches(INVERT_SELECTOR)) {
    void processImage(target)
  }
}

/** Sweep `root` for already-decoded eligible images and process them. */
export function processLoaded(root: Document | Element = document): void {
  const images = root.querySelectorAll<HTMLImageElement>(INVERT_SELECTOR)
  for (const img of images) {
    if (img.complete && img.naturalWidth > 0) {
      void processImage(img)
    }
  }
}

/** Revert every processed image under `root` (used when theme → light). */
export function revertProcessed(root: Document | Element = document): void {
  const images = root.querySelectorAll<HTMLImageElement>(REVERTABLE_SELECTOR)
  for (const img of images) {
    revertImage(img)
  }
}

/** Reactive bridge between the theme attribute and image state. */
export function onThemeChange(): void {
  if (isDarkMode()) {
    processLoaded()
  } else {
    revertProcessed()
  }
}
