/**
 * Precomputed dark-mode image swap at runtime.
 *
 * The `InvertInDarkMode` transformer wraps every label-eligible `<img>`
 * in a `<picture>` whose `<source media="prefers-color-scheme: dark"
 * srcset>` points at the precomputed `<basename>-inverted.<ext>` sibling
 * generated by `scripts/generate_inverted_variants.py`. The browser
 * fetches the right variant natively per system preference; this module
 * only swaps `img.src` when the user's manual toggle disagrees with the
 * system.
 */

import { forceHslInvertClass, invertInDarkModeClass } from "../constants"
import { invertedUrl, isInvertedUrl } from "./invertedAssets"

const INVERT_SELECTOR = `img.${invertInDarkModeClass}, img.${forceHslInvertClass}`
const REVERTABLE_SELECTOR = `img.${invertInDarkModeClass}:not(.${forceHslInvertClass})[data-invert-original-src]`

/** Reads `<html data-theme>` — set synchronously by `detectInitialState.js`. */
export function isDarkMode(): boolean {
  return document.documentElement.getAttribute("data-theme") === "dark"
}

/** True iff this image should be HSL-processed in the current theme. */
export function shouldProcess(img: HTMLImageElement): boolean {
  return img.classList.contains(forceHslInvertClass) || isDarkMode()
}

/**
 * True iff `<img>` is the direct child of a `<picture>`. Build-time
 * wrapping (`InvertInDarkMode` transformer) puts every label-eligible
 * raster in a `<picture>` whose `<source media="prefers-color-scheme:
 * dark">` lets the browser fetch the precomputed inverted variant
 * without a canvas round-trip.
 */
export function isInsidePicture(img: HTMLImageElement): boolean {
  return img.parentElement?.tagName === "PICTURE"
}

/**
 * Picture-wrapped raster path. Always stash the original src and set
 * `img.src` to the inverted variant so the attribute aligns with what
 * the user should see in dark mode (browser-picked-inverted from the
 * `<picture>` source becomes a cache hit; mismatch case actually
 * fetches). The processed marker — which CSS keys off to drop the
 * feColorMatrix fallback — is set immediately when the browser
 * already picked the inverted source, otherwise deferred to the
 * `load` event so a 404 / slow swap leaves the filter approximating
 * instead of flashing to the raw light bitmap.
 */
export function processPictureRaster(img: HTMLImageElement): boolean {
  img.dataset["invertOriginalSrc"] ??= img.src
  const inverted = invertedUrl(img.dataset["invertOriginalSrc"])
  if (img.currentSrc && isInvertedUrl(img.currentSrc)) {
    img.src = inverted
    img.dataset["invertProcessed"] = "1"
    return true
  }
  img.addEventListener(
    "load",
    () => {
      // Guard against a fast revert beating the swap to the load
      // event: the handler is `{once: true}` and stays armed, but if
      // we got reverted first (img.src now points at the original
      // again) the load fires for the wrong resource. Skipping the
      // marker there keeps a future dark-toggle from short-circuiting
      // in `processImage`.
      if (isInvertedUrl(img.currentSrc)) {
        img.dataset["invertProcessed"] = "1"
      }
    },
    { once: true },
  )
  img.src = inverted
  return true
}

/**
 * Returns `false` for ineligible images (wrong theme, already processed,
 * not yet decoded, not inside `<picture>`).
 */
export function processImage(img: HTMLImageElement): Promise<boolean> {
  if (!shouldProcess(img)) return Promise.resolve(false)
  if (img.dataset["invertProcessed"]) return Promise.resolve(false)
  if (!img.complete || img.naturalWidth === 0) return Promise.resolve(false)
  if (isInsidePicture(img)) return Promise.resolve(processPictureRaster(img))
  return Promise.resolve(false)
}

/** Restore a processed image to its original src (theme switched to light). */
export function revertImage(img: HTMLImageElement): boolean {
  const original = img.dataset["invertOriginalSrc"]
  if (!original) return false
  img.src = original
  delete img.dataset["invertProcessed"]
  return true
}

/**
 * Capture-phase document listener. `load` doesn't bubble, so capture is
 * required to catch it at the document level — which is what lets a
 * single listener installed in `<head>` cover every `<img>` in the body.
 */
export function handleLoadEvent(event: Event): void {
  const target = event.target
  if (target instanceof HTMLImageElement && target.matches(INVERT_SELECTOR)) {
    void processImage(target)
  }
}

/** Sweep `root` for already-decoded eligible images and process them. */
export function processLoaded(root: Document | Element = document): void {
  const images = root.querySelectorAll<HTMLImageElement>(INVERT_SELECTOR)
  for (const img of images) {
    if (img.complete && img.naturalWidth > 0) {
      void processImage(img)
    }
  }
}

/** Revert every processed image under `root` (used when theme → light). */
export function revertProcessed(root: Document | Element = document): void {
  const images = root.querySelectorAll<HTMLImageElement>(REVERTABLE_SELECTOR)
  for (const img of images) {
    revertImage(img)
  }
}

/** Reactive bridge between the theme attribute and image state. */
export function onThemeChange(): void {
  if (isDarkMode()) {
    processLoaded()
  } else {
    revertProcessed()
  }
}
