/**
 * Shared helpers for the precomputed dark-mode raster swap. The
 * `InvertInDarkMode` transformer emits `<picture>` markup keyed off
 * these helpers at build time; `accurateInvert.ts` uses them at
 * runtime to flip `<img src>` when the user's theme toggle disagrees
 * with `prefers-color-scheme`. The matching
 * `<basename>-inverted.<ext>` sibling files are generated by
 * `scripts/generate_inverted_variants.py`.
 */

const INVERTED_SUFFIX = "-inverted"

/**
 * Raster formats for which we precompute an inverted variant. Mirrors
 * the set in `scripts/generate_inverted_variants.py`. SVGs go through
 * the runtime `processSvgImage` fetch-and-rewrite path instead.
 */
export const INVERTIBLE_RASTER_EXTENSIONS: ReadonlySet<string> = new Set([
  ".avif",
  ".jpg",
  ".jpeg",
  ".png",
  ".webp",
])

interface UrlParts {
  stem: string
  ext: string
  tail: string
}

/** Split a URL into stem, extension (with leading dot), and tail
 * (query string + fragment). Centralizes the parsing so every helper
 * agrees on how to handle dot-positions, missing extensions, and
 * cache-buster query strings. */
function partsOf(url: string): UrlParts {
  const tailIdx = url.search(/[?#]/)
  const path = tailIdx < 0 ? url : url.slice(0, tailIdx)
  const tail = tailIdx < 0 ? "" : url.slice(tailIdx)
  const dot = path.lastIndexOf(".")
  return dot < 0
    ? { stem: path, ext: "", tail }
    : { stem: path.slice(0, dot), ext: path.slice(dot), tail }
}

export function isInvertibleRaster(url: string): boolean {
  return INVERTIBLE_RASTER_EXTENSIONS.has(partsOf(url).ext.toLowerCase())
}

/** Insert `-inverted` before the extension. `foo/bar.avif?v=2` →
 * `foo/bar-inverted.avif?v=2`. URLs without an extension pass
 * through unchanged. */
export function invertedUrl(url: string): string {
  const { stem, ext, tail } = partsOf(url)
  return ext ? `${stem}${INVERTED_SUFFIX}${ext}${tail}` : url
}

/** True iff `url`'s filename stem ends in `-inverted`. */
export function isInvertedUrl(url: string): boolean {
  return partsOf(url).stem.endsWith(INVERTED_SUFFIX)
}
