name: "Setup Build Environment"
description: "Checks out code, sets up Node and Python, installs dependencies, and caches them."
inputs:
  install-node-deps:
    description: "Whether to install Node.js and dependencies"
    required: false
    default: "true"
  install-python:
    description: "Whether to install Python and Python dependencies"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Setup base environment
      uses: ./.github/actions/setup-base-env
      with:
        install-node-deps: ${{ inputs.install-node-deps }}
        install-sharp: "true"
        cache-playwright: "false"
        cache-puppeteer: "false"
        install-python: ${{ inputs.install-python }}

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-utils dos2unix
      shell: bash

    - name: Install ffmpeg from system packages
      if: inputs.install-node-deps == 'true'
      run: |
        # Pinned to ubuntu-24.04 runner's ffmpeg version (only ffprobe is needed at build time)
        sudo apt-get install -y ffmpeg=7:6.1.1-3ubuntu5
        ffprobe -version
      shell: bash
