name: "Setup Build Environment"
description: "Checks out code, sets up Node and Python, installs dependencies, and caches them."
runs:
  using: "composite"
  steps:
    - name: Setup base environment
      uses: ./.github/actions/setup-base-env
      with:
        install-sharp: "true"
        cache-playwright: "false"
        cache-puppeteer: "false"
        cache-ffmpeg: "false"

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-utils dos2unix
      shell: bash

    - name: Download and install latest ffmpeg
      run: |
        set -e
        FFMPEG_URL="https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz"
        FFMPEG_DIR="/opt/ffmpeg"

        # Create the target directory
        sudo mkdir -p "$FFMPEG_DIR"

        # Download and extract ffmpeg, stripping the top-level directory
        curl -sL "$FFMPEG_URL" | sudo tar -xJ -C "$FFMPEG_DIR" --strip-components=1

        # Create symlinks to make ffmpeg and ffprobe available on the PATH
        sudo ln -sf "$FFMPEG_DIR"/bin/ffmpeg /usr/local/bin/ffmpeg
        sudo ln -sf "$FFMPEG_DIR"/bin/ffprobe /usr/local/bin/ffprobe

        # Verify the installation
        ffmpeg -version
      shell: bash
