name: "Setup Build Environment"
description: "Checks out code, sets up Node and Python, installs dependencies, and caches them."
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.5.1
        cache: "npm"

    - name: Cache asset dimensions
      id: asset-dimensions-cache
      uses: actions/cache@v4
      with:
        path: quartz/plugins/transformers/.asset_dimensions.json
        key: ${{ runner.os }}-asset-dimensions-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-asset-dimensions-refs/heads/main

    - name: Install Node Dependencies
      run: npm ci
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"

    - name: Install Python Dependencies
      run: pip install -r requirements.txt
      shell: bash

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-utils dos2unix
      shell: bash

    - name: Setup FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3
      with:
        ffmpeg-version: release
        github-token: ${{ github.token }}
