name: "Setup Visual Testing Environment"
description: "Sets up Node.js, installs dependencies, and optionally installs Playwright."
inputs:
  install-playwright:
    description: "Whether to install Playwright and its dependencies"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Setup base environment
      uses: ./.github/actions/setup-base-env
      with:
        install-sharp: "false"
        cache-playwright: "true"
        cache-puppeteer: "true"
        install-python: "false"

    - name: Install Playwright browsers and system dependencies
      if: inputs.install-playwright == 'true'
      run: pnpm exec playwright install --with-deps chromium webkit firefox
      shell: bash

    - name: Install ffmpeg from system packages
      run: |
        # Pinned to ubuntu-24.04 runner's ffmpeg version (only ffprobe is needed at build time)
        sudo apt-get update
        sudo apt-get install -y ffmpeg=7:6.1.1-3ubuntu5
        ffprobe -version
      shell: bash
