name: "Setup Visual Testing Environment"
description: "Sets up Node.js, installs dependencies, and optionally installs Playwright."
inputs:
  install-playwright:
    description: "Whether to install Playwright and its dependencies"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Setup base environment
      id: setup-base
      uses: ./.github/actions/setup-base-env
      with:
        install-sharp: "false"
        cache-playwright: "true"
        cache-puppeteer: "true"
        cache-ffmpeg: "true"

    - name: Install Playwright browsers and system dependencies
      if: inputs.install-playwright == 'true'
      run: pnpm exec playwright install --with-deps chromium webkit firefox
      shell: bash

    - name: Download and install ffmpeg
      if: steps.setup-base.outputs.ffmpeg-cache-hit != 'true'
      run: |
        set -e
        FFMPEG_URL="https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz"
        FFMPEG_DIR="/opt/ffmpeg"

        # Create the target directory
        sudo mkdir -p "$FFMPEG_DIR"

        # Download and extract ffmpeg, stripping the top-level directory
        curl -sL "$FFMPEG_URL" | sudo tar -xJ -C "$FFMPEG_DIR" --strip-components=1
      shell: bash

    - name: Setup ffmpeg symlinks
      run: |
        # Create symlinks to make ffmpeg and ffprobe available on the PATH
        sudo ln -sf /opt/ffmpeg/bin/ffmpeg /usr/local/bin/ffmpeg
        sudo ln -sf /opt/ffmpeg/bin/ffprobe /usr/local/bin/ffprobe

        # Verify the installation
        ffmpeg -version
      shell: bash
