name: "Setup Visual Testing Environment"
description: "Sets up Node.js, installs dependencies, and optionally installs Playwright."
inputs:
  install-playwright:
    description: "Whether to install Playwright and its dependencies"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Setup base environment
      id: setup-base
      uses: ./.github/actions/setup-base-env
      with:
        install-sharp: "false"
        cache-playwright: "true"
        cache-puppeteer: "true"
        cache-ffmpeg: "true"
        install-python: "false"

    - name: Install Playwright browsers and system dependencies
      if: inputs.install-playwright == 'true'
      run: pnpm exec playwright install --with-deps chromium webkit firefox
      shell: bash

    - name: Download and install ffmpeg
      if: steps.setup-base.outputs.ffmpeg-cache-hit != 'true'
      run: |
        set -e
        FFMPEG_URL="https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz"
        FFMPEG_DIR="/opt/ffmpeg"
        FFMPEG_TMP="/tmp/ffmpeg.tar.xz"

        # Create the target directory
        sudo mkdir -p "$FFMPEG_DIR"

        # Download with retry (GitHub CDN can return HTML on transient failures)
        for attempt in 1 2 3 4; do
          echo "Download attempt $attempt..."
          HTTP_CODE=$(curl -sL -o "$FFMPEG_TMP" -w '%{http_code}' "$FFMPEG_URL")
          if [ "$HTTP_CODE" -eq 200 ] && file "$FFMPEG_TMP" | grep -q 'XZ compressed'; then
            break
          fi
          echo "Attempt $attempt failed (HTTP $HTTP_CODE), retrying in $((attempt * 2))s..."
          sleep $((attempt * 2))
        done

        # Verify download before extracting
        if ! file "$FFMPEG_TMP" | grep -q 'XZ compressed'; then
          echo "Error: Downloaded file is not a valid .tar.xz archive"
          file "$FFMPEG_TMP"
          exit 1
        fi

        sudo tar -xJf "$FFMPEG_TMP" -C "$FFMPEG_DIR" --strip-components=1
        rm -f "$FFMPEG_TMP"
      shell: bash

    - name: Setup ffmpeg symlinks
      run: |
        # Create symlinks to make ffmpeg and ffprobe available on the PATH
        sudo ln -sf /opt/ffmpeg/bin/ffmpeg /usr/local/bin/ffmpeg
        sudo ln -sf /opt/ffmpeg/bin/ffprobe /usr/local/bin/ffprobe

        # Verify the installation
        ffmpeg -version
      shell: bash
