name: "Setup Frontend Environment"
description: "Sets up Node.js, installs dependencies, and optionally installs Playwright."
inputs:
  install-playwright:
    description: "Whether to install Playwright and its dependencies"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ">=22"
        cache: "npm"

    - name: Cache asset dimensions
      id: asset-dimensions-cache
      uses: actions/cache@v4
      with:
        path: quartz/plugins/transformers/.asset_dimensions.json
        key: ${{ runner.os }}-asset-dimensions-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-asset-dimensions-refs/heads/main

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          playwright-${{ runner.os }}-

    - name: Cache ffmpeg
      id: cache-ffmpeg
      uses: actions/cache@v4
      with:
        path: /opt/ffmpeg
        key: ffmpeg-${{ runner.os }}-master-latest

    - name: Install Node Dependencies
      run: npm ci
      shell: bash
      env:
        NODE_OPTIONS: "--max-old-space-size=4096"
        PUPPETEER_SKIP_DOWNLOAD: "true"

    - name: Install Playwright and dependencies
      if: inputs.install-playwright == 'true'
      run: npx playwright install --with-deps chromium webkit firefox
      shell: bash

    - name: Download and install ffmpeg
      if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
      run: |
        set -e
        FFMPEG_URL="https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz"
        FFMPEG_DIR="/opt/ffmpeg"

        # Create the target directory
        sudo mkdir -p "$FFMPEG_DIR"

        # Download and extract ffmpeg, stripping the top-level directory
        curl -sL "$FFMPEG_URL" | sudo tar -xJ -C "$FFMPEG_DIR" --strip-components=1
      shell: bash

    - name: Setup ffmpeg symlinks
      run: |
        # Create symlinks to make ffmpeg and ffprobe available on the PATH
        sudo ln -sf /opt/ffmpeg/bin/ffmpeg /usr/local/bin/ffmpeg
        sudo ln -sf /opt/ffmpeg/bin/ffprobe /usr/local/bin/ffprobe

        # Verify the installation
        ffmpeg -version
      shell: bash
