name: "Setup Base Environment"
description: "Sets up Node.js, pnpm, Python with uv, and common caches"
inputs:
  install-node-deps:
    description: "Whether to install Node.js and dependencies"
    required: false
    default: "true"
  install-sharp:
    description: "Whether to install sharp for Linux"
    required: false
    default: "false"
  cache-playwright:
    description: "Whether to cache Playwright browsers"
    required: false
    default: "false"
  cache-puppeteer:
    description: "Whether to cache Puppeteer browsers"
    required: false
    default: "false"
  install-python:
    description: "Whether to install Python and Python dependencies"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      if: inputs.install-node-deps == 'true'
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: "22.12.0"

    - name: Install pnpm
      if: inputs.install-node-deps == 'true'
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4

    - name: Get pnpm store directory
      if: inputs.install-node-deps == 'true'
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Restore pnpm cache
      if: inputs.install-node-deps == 'true'
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Restore asset dimensions cache
      id: asset-dimensions-cache
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: quartz/plugins/transformers/.asset_dimensions.json
        key: ${{ runner.os }}-asset-dimensions-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-asset-dimensions-refs/heads/main

    - name: Cache Playwright browsers
      if: inputs.cache-playwright == 'true'
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          playwright-${{ runner.os }}-

    - name: Cache Puppeteer browsers
      if: inputs.cache-puppeteer == 'true'
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ~/.cache/puppeteer
        key: puppeteer-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          puppeteer-${{ runner.os }}-

    - name: Install Node Dependencies
      if: inputs.install-node-deps == 'true'
      run: timeout 600 pnpm install --frozen-lockfile
      shell: bash
      env:
        NODE_OPTIONS: "--max-old-space-size=4096"

    - name: Install sharp
      if: inputs.install-sharp == 'true' && inputs.install-node-deps == 'true'
      run: pnpm install --os=linux --cpu=x64 sharp
      shell: bash

    - name: Set up uv
      if: inputs.install-python == 'true'
      uses: astral-sh/setup-uv@caf0cab7a618c569241d31dcd442f54681755d39 # v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      if: inputs.install-python == 'true'
      run: uv python install 3.11
      shell: bash

    - name: Install Python Dependencies
      if: inputs.install-python == 'true'
      run: uv sync --frozen
      shell: bash
