# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node tests

concurrency:
  group: node-tests-${{ github.event_name }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches: ["main", "dev"]
    paths:
      - "quartz/**"
      - "config/quartz/**"
      - "config/constants.json"
      - "config/javascript/**"
      - "config/typescript/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/actions/**"
  pull_request:
  merge_group:

permissions:
  actions: read
  contents: read

jobs:
  detect-changes:
    runs-on: ubuntu-24.04
    outputs:
      node: ${{ steps.changes.outputs.node }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: changes
        with:
          filters: |
            node:
              - 'quartz/**'
              - 'config/quartz/**'
              - 'config/constants.json'
              - 'config/javascript/**'
              - 'config/typescript/**'
              - 'package.json'
              - 'pnpm-lock.yaml'
              - '.github/actions/**'

  build:
    needs: detect-changes
    if: ${{ !startsWith(github.head_ref || '', 'deepsource-') }}
    runs-on: ubuntu-24.04
    timeout-minutes: 20

    strategy:
      matrix:
        node-version: ["22.12.0"]

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        if: needs.detect-changes.outputs.node == 'true'
      - name: Setup Build Environment
        if: needs.detect-changes.outputs.node == 'true'
        uses: ./.github/actions/setup-build-env
        with:
          install-python: "false"
      - if: needs.detect-changes.outputs.node == 'true'
        run: pnpm test
